package tools.aqua.dse.unittests;

import org.junit.jupiter.api.Test;
import tools.aqua.dse.preprocessing.ConstructorSummaryManager;
import tools.aqua.dse.preprocessing.Opal;
import tools.aqua.dse.preprocessing.StaticManager;

import java.util.List;
import java.util.Map;

public class StaticAnalyzerTest {
//    @Test
//    public void tes() {
//        String smtLibCode = """
//                ; -- Auxilliary
//
//                (declare-sort Object 0)
//                (declare-fun null () Object)
//
//                ; -- Summary vars
//
//                (declare-fun __object_0 () Object)
//                (declare-fun __object_0.cls () String)
//                (declare-fun __int_0 () (_ BitVec 32))
//                (declare-fun __object_0.x () (_ BitVec 32))
//                (declare-fun __object_0.a () Object)
//                (declare-fun __object_0.a.cls () String)
//
//                (declare-fun __object_0.init () String) ; <----- missing so far
//
//                ; --\s
//
//                (define-fun obj.extends ((x!0 String) (x!1 String)) Bool\s
//                  (ite (or
//                    (and (= x!0 "null") (= x!1 "LA;"))
//                    (and (= x!0 "null") (= x!1 "LB;"))
//                    (and (= x!0 "null") (= x!1 "LC;"))
//                    (and (= x!0 "null") (= x!1 "Ltest/D;"))
//                    (and (= x!0 "LA;")  (= x!1 "LA;"))
//                    (and (= x!0 "LB;")  (= x!1 "LB;"))
//                    (and (= x!0 "LB;")  (= x!1 "LA;"))
//                    (and (= x!0 "LC;")  (= x!1 "LC;"))
//                    (and (= x!0 "LC;")  (= x!1 "LB;"))
//                    (and (= x!0 "LC;")  (= x!1 "LA;"))
//                    (and (= x!0 "Ltest/D;") (= x!1 "Ltest/D;"))   \s
//                  ) true false)
//                )
//
//                ; signature for method of\s
//
//                (define-fun obj.method.of ((x!0 String) (x!1 String) (x!2 String) (x!3 String)) Bool
//                  (ite (or
//                    (and (= x!0 "LA;") (= x!1 "foo") (= x!2 "()V") (= x!3 "LA;")) \s
//                    (and (= x!0 "LB;") (= x!1 "foo") (= x!2 "()V") (= x!3 "LA;")) \s
//                    (and (= x!0 "LC;") (= x!1 "foo") (= x!2 "()V") (= x!3 "LA;")) \s
//                  ) true false)
//                )
//
//
//                ; -- Generated by spout constructor analysis
//
//                (assert (or
//                    (and (= __object_0.init "null|NULL")
//                    (= __object_0 null)
//                    (= __object_0.cls "null"))
//                    ;
//                    (and (= __object_0.init "LA;|(I)V|{__int_0}")
//                    (not (= __object_0 null))
//                    (= __object_0.cls "LA;")
//                    (= __object_0.x __int_0))
//                    ;
//                    (and (= __object_0.init "LB;|()V|")
//                    (not (= __object_0 null))
//                    (= __object_0.cls "LB;")
//                    (= __object_0.x #x00000064))
//                    ;
//                    (and (= __object_0.init "LB;|(I)V|{__int_0}")
//                    (not (= __object_0 null))
//                    (= __object_0.cls "LB;")
//                    (= __object_0.x __int_0))
//                    ;
//                    (and (= __object_0.init "LC;|(I)V|{__int_0}")
//                    (not (= __object_0 null))
//                    (not (= #x00000001 __int_0)) ; <--- parsed from a decision ...  // had to modify "!="" into "not ="
//                    (= __object_0.cls "LC;")
//                    (= __object_0.x __int_0)
//                    (= __object_0.a null)
//                    (= __object_0.a.cls "null"))
//                    ;
//                    (and (= __object_0.init "LC;|(LA;)V|{null|NULL}")
//                    (not (= __object_0 null))
//                    (= __object_0.cls "LC;")
//                    (= __object_0.x #x00000000)
//                    (= __object_0.a null)
//                    (= __object_0.a.cls "null"))
//                    ;
//                    (and (= __object_0.init "Ltest/D;|()V|")
//                    (not (= __object_0 null))
//                    (= __object_0.cls "Ltest/D;"))
//                ))
//
//
//                ; --- after initial path
//
//                (assert (not (not (and (not (= __object_0 null)) (obj.extends __object_0.cls "LB;"))))) ; -- negated
//                (check-sat)
//                (get-model)
//                """;
//    }
//
//    @Test
//    public void generateExtendsSummaryTest() {
//        StaticAnalyzer staticAnalyzer = new StaticAnalyzer("src/main/resources/example");
//
//        System.out.println(staticAnalyzer.generateExtendsSummary());
//    }
//
//    @Test
//    public void getKlassListTest() {
//        StaticAnalyzer staticAnalyzer = new StaticAnalyzer("src/main/resources/example");
//
//        System.out.println(staticAnalyzer.extractKlassesFromClassPath());
//    }
//
//
//    @Test
//    public void generatePolymorphismSummaryTest() {
//        StaticAnalyzer staticAnalyzer = new StaticAnalyzer("src/main/resources/example");
//
////        System.out.println(staticAnalyzer.generatePolymorphismSummary(List.of("A", "B", "C")));
//    }
//
//    @Test
//    public void runSpout() {
//        StaticAnalyzer staticAnalyzer = new StaticAnalyzer("src/main/resources/example");
//
//        List<Trace> traces = staticAnalyzer.performDseOnConstructor("<>LA;|(I)V|{}");
////        List<Trace> traces = staticAnalyzer.generateConstructorSummary("<>LC;|(I)V|{}");
//
//        traces.forEach(System.out::println);
//    }
//
//
//    @Test
//    public void mainTest() {
//        StaticAnalyzer staticAnalyzer = new StaticAnalyzer("src/test/resources/example");
////        System.out.println(staticAnalyzer.generateSMTProblem(null));
////        System.out.println(staticAnalyzer.generateSignaturesOfPossibleObjectsFromNondetObject(2));
////        List<Trace> traces = staticAnalyzer.generateConstructorSummary("<>LA;|(I)V|{}");
////        traces.addAll(staticAnalyzer.generateConstructorSummary("<>LA;|(I)V|{}"));
////        System.out.println(staticAnalyzer.generateSmtCodeFromConstructorSummaryTraces(traces));
//
//        System.out.println(staticAnalyzer.generateSmtCodeBluePrintForConstructorSelection(2));
//
//    }
    @Test
    public void test() {
        ConstructorSummaryManager constructorSummaryManager = new ConstructorSummaryManager("src/test/resources/example", 2);
    }

    @Test
    public void test2() {
        StaticManager staticManager = new StaticManager("src/test/resources/example", 1);
        System.out.println(staticManager.generateStaticSmtLibCode());
    }

    @Test
    public void testPolymorphy() {
        Opal opal = new Opal("src/test/resources/example");
        List<Opal.PolymorphyInformation> polymorphyInformations = opal.collectPolymorphyInformation(opal.extractKlassesFromClassPath());


        Map<Opal.PolymorphicMethodDefinition, Opal.BranchData> branchInformationMap = opal.createBranchInformationMap(polymorphyInformations);

        for (Opal.PolymorphyInformation polymorphyInformation : polymorphyInformations) {
            System.out.println(polymorphyInformation);
            System.out.println(branchInformationMap.get(polymorphyInformation));
        }


//        System.out.println(opal.generatePolymorphismSummary(opal.extractKlassesFromClassPath()));
    }
}
